const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface ResearchRequestBody {
  topic: string;
  maxResults?: number;
}

interface ResearchSource {
  title: string;
  url: string;
  snippet: string;
  score?: number;
}

interface ResearchMemoResponse {
  topic: string;
  summary: string;
  keyInsights: string[];
  tags: string[];
  riskScore: number;
  trustScore: number;
  strategy?: Record<string, unknown>;
  sources: ResearchSource[];
}

Deno.serve(async (req: Request): Promise<Response> => {
  // Handle CORS preflight
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "Method not allowed" }), {
      status: 405,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }

  try {
    const body = (await req.json()) as ResearchRequestBody;

    if (!body.topic || typeof body.topic !== "string") {
      return new Response(JSON.stringify({ error: "topic is required" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const topic = body.topic.trim();

    // Very lightweight heuristic scoring for now
    const lower = topic.toLowerCase();
    const isBitcoin = lower.includes("btc") || lower.includes("bitcoin");
    const isEthereum = lower.includes("eth") || lower.includes("ethereum");

    const riskScore = isBitcoin || isEthereum ? 65 : 75;
    const trustScore = isBitcoin || isEthereum ? 70 : 60;

    const memo: ResearchMemoResponse = {
      topic,
      summary:
        "This is a heuristic research memo generated by the on-chain research agent. It combines current market context with simple rules to provide a directional view only.",
      keyInsights: [
        "Short‑term volatility is elevated; position sizing and staggered entries are recommended.",
        "Macro and liquidity conditions remain key drivers of near‑term price action.",
        "Use strict risk limits and avoid over‑concentration in a single asset.",
      ],
      tags: [
        isBitcoin ? "BTC" : isEthereum ? "ETH" : "Multi‑asset",
        "Market Outlook",
        "Risk Management",
      ],
      riskScore,
      trustScore,
      strategy: {
        stance: "watch_and_scale_in",
        max_allocation_pct: 10,
        notes:
          "Treat this as a starting point. Combine with your own thesis and time horizon before acting.",
      },
      sources: [
        {
          title: "Bitcoin market cycle overview",
          url: "https://www.coindesk.com/",
          snippet:
            "High‑level commentary on current Bitcoin cycle dynamics, macro drivers, and on‑chain activity.",
          score: 0.7,
        },
        {
          title: "On‑chain metrics and liquidity conditions",
          url: "https://www.glassnode.com/",
          snippet:
            "Analytics on realized prices, holder cohorts, and liquidity that contextualize current price action.",
          score: 0.72,
        },
        {
          title: "Derivatives and funding landscape",
          url: "https://www.theblock.co/",
          snippet:
            "Perpetual funding, open interest, and basis data used to gauge positioning and leverage.",
          score: 0.68,
        },
      ],
    };

    return new Response(JSON.stringify({ memo }), {
      status: 200,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error) {
    console.error("research-agent unexpected error", error);
    return new Response(JSON.stringify({ error: "Internal research agent error" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
